### ISSUE TITLE
Callback when logout success

### ISSUE THREAD

**Issue by chauhq** [line/line-sdk-starter-android#12]
When I call authManager.logout(), how to know it logout success to me do something ?

**Comment by GuitarSucks** [comment]
You can tray catch like below , but basically you don't need to worry of logout success since it will basically remove the local access token cache.

`try {
            authManager.logout().get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
        }`
