### ISSUE TITLE
FAILED_A2A_LOGIN when install line app into device

### ISSUE THREAD

**Issue by chauhq** [line/line-sdk-starter-android#13]
When my device do not install line app I login any account sucessfully but I install line app to device when login It notify error FAILED_A2A_LOGIN, please explain for me about that error. thanks

**Comment by cyq7on** [comment]
Hello,did you resolve it?There are no reply,I'm disappointed to line.

**Comment by chauhq** [comment]
Hi, not yet, It still is bug.

**Comment by royl2k90** [comment]
I can login on first try, no errors. Did you download the sample codes, input your LINE channel ID in manifests and run in Android Studio?

**Comment by cyq7on** [comment]
Yeah,of cource.If not,web-logining will fail too.

**Comment by royl2k90** [comment]
When I have LINE app, it just ask me to log in email and password, then it send a SMS code to my number and I verify it then I login successfully. Do you have the error log of failed login authentication?

**Comment by cyq7on** [comment]
Just as the title,FAILED_A2A_LOGIN

**Comment by royl2k90** [comment]
https://www.facebook.com/playok.sp33dcub3r

Add me on Facebook and you can see the video of LINE login from sample app.

**Comment by cyq7on** [comment]
3q,I'll do it as soon as getting a good network.

**Comment by royl2k90** [comment]
You cannot access Facebook now? You have a network to comment on Github but no Facebook? Which country are you from? I am from Singapore, nice to meet you and all developers here.

**Comment by cyq7on** [comment]
Yeah,I can not now.Nice to meet you,too.I am from China.

**Comment by royl2k90** [comment]
Please refer to https://github.com/line/line-sdk-starter-android/issues/14 for the solution.

**Comment by royl2k90** [comment]
You can close this issue thereafter. Thanks.
