### ISSUE TITLE
How to send LINE message from Java code?

### ISSUE THREAD

**Issue by royl2k90** [line/line-sdk-starter-android#15]
Now I am able to login LINE and display my username and profile picture when I click the "Try API" button. Next, I want to display my friend lists using `apiclient.getFriends()`. Any sample code?

Anyone knows how to create a Java API to send LINE message to friends?
I got the skeleton code but I do not know how to implement it.

```
class LineMsg {
    public void SendMsg(String username, String msg) {
        //username is the friend name that I want to send a message to
    }
}
```

Then I have a main method.

```
public void main(String[] args) {
    LineMsg linemsg = new LineMsg();
    linemsg.SendMsg("username of LINE friend","Hello World!")
}
```

Then I need to zip up as JAR file so my friend can import the JAR file and send LINE message to contacts. The purpose of doing this is to replace the SMS function which have high cost. So we want to send to our clients using the LINE method by Java code. If anyone knows how to implement, please give some ideas. Thanks.

**Comment by royl2k90** [comment]
The FRIEND LIST permission is not available to public at the moment, the developer @GuitarSucks  said this.

What else can I do other than login the LINE and display the username and profile picture, and other profile details?

**Comment by GuitarSucks** [comment]
Hi
Unfortunately we don't provide FRIENDS permission due to policy issues. So currently its only display name , profile picture and status message.
In the future we are trying to to provide FRIENDS which match our policy, but could be close to FB way.
There will be also a new API in the future to provide some other information from user, If the user approves.

Regards

**Comment by royl2k90** [comment]
Noted and thanks. I will give a try on GCM in the meantime.
