### ISSUE TITLE
An error occurred. Please try again.

### ISSUE THREAD

**Issue by DanteAndroid** [line/line-sdk-starter-android#16]
I created the channel for our app, and entered the required technical information, when I try to login in the demo, it shows the error, and **no any log**. Could you help me?
```
		LineAuthManager authManager = LineSdkContextManager.getSdkContext().getAuthManager();
		authManager.login(this).addFutureListener(
				new LineLoginFutureListener() {
					@Override
					public void loginComplete(LineLoginFuture future) {
						switch (future.getProgress()) {
						case SUCCESS:
							SharedPreferences settings = getSharedPreferences("lineauth", MODE_PRIVATE);
							// Store credentials to, for example, send in a webview activity to a server.
							// Developers should not have to worry about these values if they are only calling
							// APIs from the Android application.
							settings.edit()
									.putString("mid", future.getAccessToken().mid)
									.putString("accesstoken", future.getAccessToken().accessToken)
									.putString("refreshtoken", future.getAccessToken().refreshToken)
									.putLong("expire", future.getAccessToken().expire)
									.apply();
							displayCroutonOnMainThread("Logged in!", Style.INFO);
							logger.info("Login success!");
							break;
						case CANCELED:
							displayCroutonOnMainThread("Don't cancel login!", Style.ALERT);
							logger.info("Login canceled!");
							break;
						default:
							displayCroutonOnMainThread("An error occurred. Please try again.", Style.ALERT);
							logger.info("Login error!");
							break;
						}
					}
				});
```

**Comment by DanteAndroid** [comment]
even if I use my app(with my package name in the channel, and corresponding signature), the login still failed(as it goes into the default branch).
However, when I cancel the login, sdk recognize it correctly.

**Comment by DanteAndroid** [comment]
I tried, web login is OK, but with the client it still failed.

**Comment by GuitarSucks** [comment]
@DanteAndroid 
Following are most common cause for this issue.
1. The package name set on Developers site is incorrect
2. The package signature on Developers site is incorrect
3. The Login user you are trying is not in the developer role of your Channel

Please notice that even though you set the correct information on Developers site, it will take few minutes to be applied.

**Comment by GuitarSucks** [comment]
For your case it will be either 1 or 2

**Comment by DanteAndroid** [comment]
@GuitarSucks What if I told you these are correct? We checked and tried many times. If those are incorrect, re-create a Line account won't help.

**Comment by DanteAndroid** [comment]
Hey, guys, sorry to bother, but is there any `ShareSDK` for Line?

**Comment by willyao94** [comment]
Hi, I've stumbled upon this problem today as well and I was able to get it to work following GuitarSucks' instructions. The note for it to take a few minutes to apply in particular was helpful.

**Comment by lekenny** [comment]
when i use authManager.loginByAccount(this).addFutureListener(....);
it's success

but i use authManager.login(this).addFutureListener(....);
not work;
catch { [Error: Login failed] framesToPop: 1, code: '401' }
@GuitarSucks   
how to get The package signature , i got MD5 SHA1 and key hashes  i don't know which one is need

**Comment by DanteAndroid** [comment]
Just to mention, If these methods won't help, just try another Line developer account.
