### ISSUE TITLE
Lineの認証画面から復帰した時に 「FAILED_A2A_LOGIN errorCode=2」

### ISSUE THREAD

**Issue by helloooideeeeea** [line/line-sdk-starter-android#3]
Line Login Platformにてログイン認証を実装する事になり、
「line-sdk-starter-android」のソースを参考にさせていただいています。

Lineの認証画面から復帰した時に以下のエラーが出て、ログインに失敗します。
FAILED_A2A_LOGIN errorCode=2

どういった原因が考えられますでしょうか？
以下は、該当するソースになります

 LineAuthManager authManager = LineSdkContextManager.getSdkContext().getAuthManager();
        authManager.login(this).addFutureListener(
                new LineLoginFutureListener() {
                    @Override
                    public void loginComplete(LineLoginFuture future) {
                        Throwable cause = future.getCause();
                        if (cause instanceof LineSdkLoginException) {
                            android.util.Log.e(TAG, String.format("Error message: %s", cause.getMessage())); <- FAILED_A2A_LOGIN errorCode=2
                        }
                    }
                });

**Comment by GuitarSucks** [comment]
FAILED_A2A_LOGIN Error is mostly caused if the apk signature is different from the technical configuration on channel console.
Please confirm it and if you change the configuration signature, please wait some time so it can be applied.

**Comment by helloooideeeeea** [comment]
@GuitarSucks 

> FAILED_A2A_LOGIN Error is mostly caused if the apk signature 

I tried to check apk signature 10 or more times.(it's Google Play apk's signature)
What possible causes of the other ?

thanks

**Comment by wujianyin** [comment]
There may be your channel in the development of the state(the status is developing), this time can only get your developer's account authorization, other accounts authorization failed

**Comment by helloooideeeeea** [comment]
@wujianyin thanks! we got the response「login success」!

**Comment by DrKein** [comment]
OMG.. 
Why don't you describe this on developer's document?

**Comment by KevinYaoooooo** [comment]
@DrKein Yeah i thought this way too !

**Comment by GuitarSucks** [comment]
We will be revising the docs in the near future. For now we have added FAQ pages that can help you.
https://developers.line.me/faq

**Comment by KevinYaoooooo** [comment]
I have one question: How can i get the FRIEND LIST permission?

**Comment by GuitarSucks** [comment]
@Kevin-Misfit 
Sorry it is not provided to public at this moment.

**Comment by KevinYaoooooo** [comment]
So, it's only for internal use? but why did you guys write these information that more than just login on the document,  make us believe we can get more permissions, and we can not get these, so sad!!

**Comment by GuitarSucks** [comment]
@Kevin-Misfit 
I meant its not open to public. It could be allowed in some strategy / business partnership cases.
I'll be working to reduce those gaps for you guys

**Comment by KevinYaoooooo** [comment]
Hi, i'm wondering how can i auth succeed when i first add my develop account to the channel, because right now ,it's always auth failed, even i'm already added my develop account to the channel, and email also been verified

**Comment by saityoukou** [comment]
me too.
already confirm
1. signature keystore(myself keystore's SHA1 without ":")
2.Role for Developer(add official email)

but don't work.
how to succeed login??

**Comment by KevinYaoooooo** [comment]
@saityoukou same, need hellllllllp!!!

**Comment by saityoukou** [comment]
@Kevin-Misfit 
1.confirm your channel role
[Assign a role to a new user] 

★:confirm you'r email. after add role line will send confirm mail to you.

2.use newest sdk
current is line-android-sdk-3.1.19.zip

3.check signature keystore SHA1

**Comment by KevinYaoooooo** [comment]
I've already did step 1, step 2. i used a 3.1.16, step 3 is ok, but still not working

**Comment by saityoukou** [comment]
@Kevin-Misfit  please use 3.1.19.

**Comment by KevinYaoooooo** [comment]
@saityoukou  Can i see the change log of SDK?

**Comment by saityoukou** [comment]
@Kevin-Misfit i don't know. no found SDK release note.

**Comment by GuitarSucks** [comment]
Release note are currently shown on Developers site news.
https://developers.line.me/news?ny=2016

**Comment by GuitarSucks** [comment]
@Kevin-Misfit 
Please show provide logcat info
