### ISSUE TITLE
line sdk have so many warning.

### ISSUE THREAD

**Issue by saityoukou** [line/line-sdk-starter-android#5]
this is build message.

Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(jp.line.android.sdk.a) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(jp.line.android.sdk.a.a.a.b) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(jp.line.android.sdk.a.c.f) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(jp.line.android.sdk.a.c.c) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(jp.line.android.sdk.a.c.e) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is _not_ an inner class.

**Comment by royl2k90** [comment]
I have this error too. What JDK version are you using? What build tools version? Did you add anything in proguard rules file?

**Comment by royl2k90** [comment]
@saityoukou in your build.gradle of module file, **comment out the line "targetCompatibility JavaVersion.VERSION_1_7**"

Because the error log says "The recommended solution is to recompile the class from source, using an up-to-date compiler and **without specifying any "-target" type options**."

I am using Android Studio 2.1.2.
First, I set my JAVA_PATH to point to **JDK 1.7** of my Program Files.
Then I open Android Studio and open the build.gradle module file.
1) Set the **Build Tools version to 23.0.3** instead of 24.0.0-rc3 (24.0.0-rc3 is for Java version 1_8). For me, my latest is 23.0.3.
2) Then **comment out the jackOptions set to true**, do not include that in the defaultConfig {...} if you are not using Java version 1_8.

If you were from Eclipse, you **do not need to add the appcompat_v7 JAR file** in Android Studio "lib" folder. Delete off the file from the Version Control Tab in the bottom left corner window pane.

Add the following for your proguard-rules file.

```
-keep class com.newrelic.** { *; }
-dontwarn com.newrelic.**
-keepattributes Exceptions, Signature, InnerClasses
```

Add the following in gradle.properties file in C:\Users\"yourName".gradle (create gradle.properties file if not exist). This is for faster gradle build time. It takes me at most 10 seconds.

```
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configureondemand=true
```

Try to exit Android Studio and open again. Make file and Run. You should not see the warnings again.

**Comment by rahulnarang21** [comment]
i got this error, and i have tried your solution, but i got the same error , i am developing a real time application and i have added mobikwiksdk in my app 10 days earlier, i didnt got any error, but now today, i got this error , please tell me what to do.

**Comment by rahulnarang21** [comment]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0\bin\java.exe'' finished with non-zero exit value 2, 

warning are same as defined above and the error is this.

**Comment by rahulnarang21** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

```
defaultConfig {
    applicationId "roastnow.roastnow"
    minSdkVersion 19
    targetSdkVersion 23
    versionCode 1
    versionName "1.0"

}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
```

}

dependencies {
    testCompile 'junit:junit:4.12'
    compile project(':MobiKwik_SDK_V2.0.1')
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.mcxiaoke.volley:library-aar:1.0.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.google.android.gms:play-services:9.0.1'
    compile 'com.google.code.gson:gson:2.3'
}

this is my gradle.build file

**Comment by rahulnarang21** [comment]
i have just deleted the project and import it again, again import that mobikwiksdk and now the app is running but showing the warnings again as same

**Comment by royl2k90** [comment]
@rahulnarang21 Are you using Eclipse or Android Studio? Do the warnings appear during every build or only the first build? Include only the libraries that you need and clean the project. What is this mobikwiksdk about?

**Comment by royl2k90** [comment]
Please show me the tutorial about what you have done so far, and I try to see if I have the same error. However, this issue is related to LINE application, not mobikwiksdk.

**Comment by rahulnarang21** [comment]
i am using android studio, and mobikwik is the payment gateway which we have purchased from mobikwik for the transanction from our application.
What exactly i will send you, the whole project or what?

**Comment by rahulnarang21** [comment]
and thnx sir, for showing your concern towards this

**Comment by rahulnarang21** [comment]
1 thing sir, this problem occurs when i import this project on another android studio in another pc and installing the application in the same mobile device, it asks me for that    "the app already being installed in this device with different signatures, Do you want to remove the signed data of the application" , i clicked yes and the application is built on the device from my new pc.
when i again checking my old application on old android studio on the same device, first i uninstall the application which i have installed earlier by new android studio and then install it using old , then i got this error.

**Comment by rahulnarang21** [comment]
again i got the error and my app was not getting installed. and i just
solved this, by downgrading the google play services version from 9.0.1 to
8.4.1, but i didnt actually got to know why this error coming from the
version of google play. please tell me the reason if you know. and why the
warning coming by importing mobikwik sdk?

**Comment by ipulcrimx** [comment]
Hi....
I got the very same error. But, I build my app in Unity player. How should I do to resolve this problem?

**Comment by rahulnarang21** [comment]
I have just added multi dex enabled and restarted the project by clearing
caches n solved d problem

I don't have knowledge about unity player

**Comment by nikhilinnovationm** [comment]
Can anyone tell me what is the proguard rule for mobikwik. I am unable to find it.
