### ISSUE TITLE
I meet a login problem

### ISSUE THREAD

**Issue by chonglv** [line/line-sdk-starter-android#6]
when I try to login in by the sample codes from this project, I always meet
the same error message as below:
jp.line.android.sdk.exception.LineSdkLoginException:  error=FAILED_WEB_LOGIN, errorCode=401

can u help to check it ?

**Comment by KevinYaoooooo** [comment]
same problem with me, i've already assign a role to our test co-work, but still not working.

**Comment by GuitarSucks** [comment]
There are several reasons
1. Have you applied a channel to develop?
2. Have you set the SHA1 of your application on Channel Console ? and have you also use the same signature on your App when testing?
3. Is the Channel ID set correctly on your app?
4. Is the person that is trying to login have a developer role on your channel ?

**Comment by KevinYaoooooo** [comment]
Already did all steps, but still met problem: Line authorize failed, error message: **jp.line.android.sdk.exception.LineSdkLoginException:  error=FAILED_WEB_LOGIN, errorCode=446**

**Comment by KevinYaoooooo** [comment]
How long will the developer role affected after i the developer accept the invite and verified the email and can start test?

Currently, the login process will always return a error:  **error=FAILED_A2A_LOGIN, errorCode=2**
So i'm wondering how long the developer account will affected?

**Comment by chonglv** [comment]
finally, I work around this issue. You need to add a Developer/Channel Editor role for your channel.
Waiting for some time, maybe a little longer, then try again. bingo! got it.
