### ISSUE TITLE
I met a login network error problem

### ISSUE THREAD

**Issue by KevinYaoooooo** [line/line-sdk-starter-android#8]
![device-2016-03-29-143718](https://cloud.githubusercontent.com/assets/12027816/14099910/0d7dcd68-f5bc-11e5-8ec1-40d2d3a9aadb.png)

I'm in China, i'm integrating with line, used a line login for our JP customers, but when i test line login, some phones are just doing fine, on Mi4 phone always met this problem(see screenshot above), please help me or give me some suggestion on this.  thanks a lot!

**Comment by GuitarSucks** [comment]
@Kevin-Misfit 
Sorry our servers IP are blocked by the great firewall....
